import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const VCR_OSD_MONO = localFont({
  src: "./fonts/VCR_OSD_MONO.ttf",
  variable: "--font-vcr-osd-mono", // Consistent naming
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Elevator Crowd Management",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${VCR_OSD_MONO.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
